# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lgToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgToken', models.CharField(db_column='lg_token', max_length=120)),
                ('status', models.IntegerField(db_column='status', default=0)),
                ('user', models.CharField(blank=True, db_column='user', max_length=100, null=True)),
                ('expiredTime', models.DateTimeField(db_column='expierd_time')),
            ],
            options={
                'db_table': 'lgToken',
            },
        ),
    ]
